snyk/dep-graph

src/core/create-from-json.ts, src/core/errors/custom-error.ts, src/core/errors/index.ts, src/core/errors/validation-error.ts, src/core/validate-graph.ts, src/index.ts, test/core/create-from-json.test.ts
Throw a custom ValidationError for any issues when validating incoming
DepGraphData payloads. This is to allow callers to distinguish between
unexpected errors and validation-failures.
I'm still a little unconvinced that this is better than simply adding an error
code... what do you think?
=> feat: custom ValidationError

src/core/types.ts
this simplifies the use for the consumers of the lib, when in example
someone wants to cast from `PkgInfo` to `Pkg`
=> fix: same TypeScript type for .version in Pkg & PkgInfo

src/legacy/index.ts, test/legacy/from-dep-tree.test.ts
When creating from a tree that contains same pkg with different versions
which share a `<prefix>|`, it would have created an invalid graph, due
to uncareful split by `|`.
=> fix: tree-to-graph: miss-handling of versions containing a '|' char

src/core/validate-graph.ts, test/core/create-from-json.test.ts, test/legacy/from-dep-tree.test.ts
this can actually happen in npm, and doesn't break currently exposed methods
=> fix: drop validation for root pkg having only a single node

src/legacy/index.ts, test/legacy/from-dep-tree.test.ts
This shouldn't happen - but did and can due to bugs in the various sources that build the dep-trees, and it's better to just skip a `null` dependency rather than failing completely
=> fix: depTreeToGraph - skip invalid null dependencies

src/legacy/index.ts, test/fixtures/cyclic-dep-graph.json, test/fixtures/goof-dep-tree.json, test/fixtures/gradle-dep-tree.json, test/fixtures/maven-dep-tree.json, test/fixtures/os-apk-dep-tree.json, test/fixtures/os-apt-dep-tree.json, test/fixtures/os-deb-dep-tree.json, test/fixtures/os-deb-graph.json, test/fixtures/os-rpm-dep-tree.json, test/fixtures/pip-dep-tree.json, test/fixtures/sbt-dep-tree.json, test/helpers.ts, test/legacy/from-dep-tree.test.ts, test/legacy/to-dep-tree.test.ts
Exposes a way to convert dep-graph's to the legacy tree format.
"Package manager" and "package type" must be handled out of band by the
consumer, as "package manager" exists only on dep-graphs and "package
type" exists only on legacy trees.
Given legacy tree's have a very ill-defined structure, the conversion
can be lossy. This commit adds test fixtures that cover all of the data
that is preserved in conversion. If something is not in a fixture, then
it is not guaranteed to be preserved (e.g. package licence metadata).
It is expected that future releases of this library will formalise and
preserve more of the semi-structured data that exists on legacy trees, as
needed.
=> Convert to legacy format

src/legacy/index.ts, test/legacy/to-dep-tree.test.ts
to maintain backwards compatibility with Rubygems trees that were
assumed to have the `.type` field, and with some other legacy parts that
used to set `.type` with the name of the package-manager
=> feat: graphToDepTree sets .type to pkgManager.name

src/legacy/event-loop-spinner.ts, src/legacy/index.ts
To not block the event-loop in potential blocking functions like the ones converting to and from the legacy dep-tree, we yield to the event-loop via `setImmediate()` during loops/recursions. 
This PR improves this to make sure we don't yield too much, by checking that at-lest 50ms passed since previous `setImmediate()`.
=> fix: EventLoopSpinner for less setImmediate yields

src/core/dep-graph.ts
- hasCycles() can be very expensive, so memoize it
- eyeball it
Something like this on a complex graph should show an order of magnitude improvement in total time:
```js
console.time('calculate complexity');
depGraph
.getPkgs()
.map((pkg) => depGraph.countPathsToRoot(pkg))
.reduce((acc, pathsToRoot) => acc + pathsToRoot, 0);
console.timeEnd('calculate complexity');
```
Using a particularly pathological graph this went from > 60 seconds down to 14 ms.
=> fix: memoize hasCycles()

src/legacy/event-loop-spinner.ts
Long-running tasks (like graph conversions) are much slower than they should be. It's possible it happens because the task yields to spinner after 10 ms _since the start of the spin_ have elapsed. We should switch it to 10 ms since the end of spin, to ensure that we have stable 10ms chunks.
=> fix: do not yield to spinner until 10ms actually elapsed

package.json
- we use semver to check the schema version of the graph data but failed to include it as a direct dependency
=> fix: add semver dependency

README.md, src/core/dep-graph.ts, src/core/types.ts, src/legacy/index.ts, test/fixtures/cyclic-dep-graph.json, test/fixtures/goof-graph.json, test/fixtures/labelled-dep-tree.json, test/fixtures/labelled-graph.json, test/fixtures/os-deb-graph.json, test/fixtures/simple-dep-tree.json, test/fixtures/simple-graph.json, test/legacy/__snapshots__/from-dep-tree.test.ts.snap, test/legacy/from-dep-tree.test.ts, test/legacy/to-dep-tree.test.ts
docker layer information is the first use case, but surely not latest
where we want to store additional information on the package level.
this commit extends both depTree and pkgGraph to possibly contain
arbitrary key value information for clients to use as they wish.
=> feat: Introducing labels

src/core/create-from-json.ts, test/core/create-from-json.test.ts
- check for valid schema version before checking range
- `semver@6.1.0` throws an exception when testing an invalid range
- so pre-check the input to ensure we throw the correct exception
=> fix: check for valid schema version before checking range

src/legacy/index.ts, test/fixtures/pruneable-tree-multi-top-level-deps-pruned.json, test/fixtures/pruneable-tree-pruned.json
We need to save "pruned" attribute to display it in the Registry.
Gee, we have exactly the tool for that: labels!
=> fix: make "pruned" a label, to preserve during the conversion to graph

README.md, src/index.ts
Exports `DepGraphBuilder` so new DepGraph instances can be created.
=> feat: allow creation of new DepGraph

.github/CODEOWNERS
Sets @snyk/arch as the owners for this repo
=> chore: add GitHub code ownership file

src/index.ts, test/core/builder.test.ts
export `Pkg` & `PkgInfo` TS types, as they are used in the already exported `DepGraph` type, and are useful to the consumers of the lib
=> fix: export Pkg & PkgInfo TS types

README.md, src/core/types.ts, src/legacy/index.ts, test/fixtures/npm-cyclic-dep-tree.json, test/legacy/from-dep-tree.test.ts
Add `pruned` label definition to graph. The three options we set for it are `true` - for pruned in CLI with the --pruned option, `cyclic` - for cyclic deps pruned like in npm, `seen` - if the same subtree was already seen when run with --prune-repeated-dependencies
=> feat: add pruned label to graph

README.md, src/core/dep-graph.ts, src/core/types.ts, test/core/builder.test.ts, test/core/create-from-json.test.ts, test/legacy/from-dep-tree.test.ts
This won't return the root package even if the root is a dependency by itself (a.k.a cycle with root)
=> feat: .getDepPkgs() to get all pkgs except root

README.md
Based on  src/legacy/index.ts:19, dependencies is not a mandatory key.
Aligns README with the implementation
=> docs: aling DepTree interface with code

src/core/dep-graph.ts, test/core/stress.test.ts
A customer cannot scan their project with a supposedly very large dependency graph because as soon as it reaches our back-end, we get a stack overflow error. It was identified that the error is due to the combination of Array.push() and the spread operator.
For reference: https://github.com/nodejs/node/issues/16870
To reproduce, create an array of size 2^17 then do [].push(...myArray);.
This fix replaces all uses of push() and spread with a simple loop.
```
node
> const example = [];
undefined
> for (let i = 0; i < 2 ** 23; i++) {
...     example.push('o');
... }
8388608
> [].push(...example);
Thrown:
RangeError: Maximum call stack size exceeded
>
```
[Zendesk Ticket 2194](https://snyk.zendesk.com/agent/tickets/2194)
=> fix: avoid stack overflow with spread operator

README.md, src/core/create-from-json.ts, src/core/dep-graph.ts, src/legacy/index.ts, test/core/create-from-json.test.ts, test/helpers.ts, test/legacy/from-dep-tree.test.ts
Corrects two mistakes:
* some tests were using `.sort()` on a `PkgInfo[]` list. Without the comparison function, this sort was doing nothing. The tests were passing just by accident.
* `PkgInfo.version` was set to `null` sometimes and was advertised as `null`-able in the README. This was fixed, now only `undefined` should be used.
Since it introduces a light breakage (correction) of the library interface, this is being submitted as "feat" rather than "fix" or "tests".
=> feat: update tests and correct type definition

README.md, src/core/dep-graph.ts, src/core/types.ts, test/core/direct-deps-leading-to.test.ts
Add a public method to get the direct dependencies which introduced the specified package.
=> feat: add directDepsLeadingTo public method

src/legacy/index.ts, test/fixtures/pruneable-tree-multi-top-level-deps-pruned.json, test/fixtures/pruneable-tree-multi-top-level-deps.json
Fixes a label instance reuse bug during pruning.
Why is this a fixture update and not an explicit focused test?
- It's an implementation bug that does not deserve negative testing
=> fix: Fix label instance reuse bug during pruning

src/legacy/index.ts, test/fixtures/os-linux-scratch-dep-graph.json, test/fixtures/os-linux-scratch-dep-tree.json, test/legacy/to-dep-tree.test.ts
Imported scratch images have linux as a package manager
DepTree should include targetOS.
To support scratch images import, we're currently setting the pkgManager on these projects as `linux`.
Needed to add it so `targetOS` will be included in the depTree.
Added a test with fixtures, `targetOS` should be included in the depTree after conversion.
Import a docker project with container image built from scratch.
i.e `snyk monitor --docker busybox:1.31.1`
Dep graph should be:
```
{
"schemaVersion": "1.2.0",
"pkgManager": {
"name": "linux",
"repositories": [
{
"alias": "unknown:0.0"
}
]
},
"pkgs": [
{
"id": "docker-image|busybox@1.31.1",
"info": {
"name": "docker-image|busybox",
"version": "1.31.1"
}
}
],
"graph": {
"rootNodeId": "root-node",
"nodes": [
{
"nodeId": "root-node",
"pkgId": …
```
=> feat: support scratch images

.travis.yml, tsconfig.json
Node 6 reached End-Of-Life at April 30, 2019.
The snyk CLI was the only dependant we had that supported Node 6, and it
recently deprecated Node 6 too: https://github.com/snyk/snyk/releases/tag/v1.301.0
By updating the `target` to `es2017` in `tsconfig.json` we get native `async/await`
=> feat: drop Node 6 support

package.json
specify min required node version as 8, following the drop of Node 6 support in https://github.com/snyk/dep-graph/pull/53.
=> fix: package.json: update min supported node to 8

src/core/create-from-json.ts, src/core/dep-graph.ts, src/core/validate-graph.ts, src/legacy/index.ts, test/helpers.ts, test/legacy/from-dep-tree.test.ts, test/legacy/to-dep-tree-prune.test.ts, test/legacy/to-dep-tree.test.ts
- Just use JavaScript
- Could not remove `lodash` completely because `isEqual` is tricky
- Was tempted to switch to `lodash.isequal` package, but that
will make reverting our fork harder, so leaving as-is for now
Lodash is big and has become less relevant as JavaScript has matured
=> fix: Reduce lodash usage

package.json
- Rolls `semver` back to 6
- `semver` 7 dropped support for Node 8 (which we still support for now)
https://github.com/snyk/dep-graph/pull/58#issuecomment-629650124
=> fix: Roll `semver` back to 6

package.json, src/core/dep-graph.ts, test/helpers.ts
Swap out `@snyk/lodash` for `lodash.isequal`, our only use.
Bump some stuff while we're here.
=> feat: drop @snyk/lodash dependency, + bumps

package.json
Typescript 3.9 breaks sinon stubbing in some of our APIs,
which breaks tests in other services. It does not break
tests in this service. Those other services need to be
fixed to not need this, but, for now, let's just rollback.
=> fix: hack: revert typescript -> 3.8, sinon fix

package.json
This reduces our transitive vulns, and should shrink our install size for direct dependants.
Changes: Just the `switch lodash to dot packages` change. https://github.com/snyk/graphlib/commits/master
=> fix: upgrade graphlib: no metapackage lodash

package.json, src/core/builder.ts, src/core/create-from-json.ts, src/core/dep-graph.ts, src/core/validate-graph.ts
- Lodash has released a non-breaking update that fixes the vulns
we were avoiding, so we can stop using our fork
=> fix: Switch back to `graphlib`

package.json, src/index.ts
This forces applications to pick up source-map-support, which is not
always wanted, and may be causing them issues.
=> feat: libraries do not register source maps

src/legacy/index.ts, test/legacy/stress.test.ts
It adds memoization in the `graphToDepTree`
This will result in reused objects in a tree instead, for example the following graph
```
A --> B --> D
\-> C --> B
```
Instead of creating `B --> D` twice (as today), it will reuse the B subtree
=> feat: add memoization to when converting a graph into a tree

src/legacy/index.ts
Like https://github.com/snyk/dep-graph/pull/73 (which affects graphToDepTree), It adds memoization in the depTreeToGraph
For a **very large tree** (that was generated using the memoization from https://github.com/snyk/dep-graph/pull/73), it reduced the time from 20000ms to less than 200ms
=> feat: add memoization when converting tree to graph

.gitignore, src/core/builder.ts, test/core/builder.test.ts
Exposes `DepGraphBuilder._pkgs` using public get property `packages`. 
Poetry lockfiles can have circular dependencies. In an effort to fix a bug that arose out of this in `snyk-poetry-lockfile-parser` repo, I found a need to access the packages that have already been added.
To see the packages already added, consumers of `DepGraphBuilder` have to keep a local record of the packages added or alternatively call `build`.
=> feat: expose packages that have been added in builder

src/core/create-from-json.ts, src/core/dep-graph.ts
There are a few places where the dep graph function names are not quite enough to explain the intent / usages (or at least, I could not easily understand)
This patch adds some small docstrings so that IDEs can show them, rather than needing to open the dep graph source / docs.
=> fix: Add some minimal function docs

.gitignore, package.json, scripts/benchmark.js, src/graphlib/alg/dfs.ts, src/graphlib/alg/topsort.ts, src/graphlib/graph.ts
Indiscriminately replace `lodash.has` with `in`. This is a 40% speedup for loading a graph.
Most of the top profiling entries are related to `lodash.has`:
```
[JavaScript]:
ticks  total  nonlib   name
107    2.0%   11.5%  RegExp: \.|\[(?:[^[\]]*|(["'])(?:(?!\1)[^\\]|\\.)*?\1)\]
69    1.3%    7.4%  RegExp: ^\w*$
65    1.2%    7.0%  *createFromJSON dist/core/create-from-json.js:13:24
50    0.9%    5.4%  *hasPath nm/lodash.has/index.js:551:17
50    0.9%    5.4%  *<anonymous> dist/graphlib/alg/dfs.js:35:38
37    0.7%    4.0%  *setEdge dist/graphlib/graph.js:323:12
21    0.4%    2.3%  *successors dist/graphlib/graph.js:233:15
12    0.2%    1.3%  *isKey nm/lodash.has/index.js:596:15
11    0.2%    1.2%  *<anonymous> dist/core/validate-graph.js:16:48
10    0.2%    1.1%  *getMapData …
```
=> feat: remove lodash.has

src/core/dep-graph.ts
In [PR 80](https://github.com/snyk/dep-graph/pull/80) I added cache for the `pathsToRoot` function
It created side-effects in some places, i.e. in registry, there's a code that mutates the result with `.reverse()`
We'll create a different PR with the cache in the future
=> fix: remove cache in pathsToRoot

.npmrc
This patch adds a `.npmrc` file with `package-lock=false` to prevent devs generating local lockfiles. These wouldn't be committed due to the `.gitignore`, but they will cause weird issues locally that wouldn't exist in CI
=> chore: Add .npmrc file

src/legacy/index.ts
I'm gradually removing all usage of the tree to graph conversions from our internal systems. We should begin to surface that these structures are being removed (via deprecation warnings) so there aren't new uses of trees being created
=> feat: Deprecate all legacy exports

.travis.yml, package.json
Add support for node 16, which involves just updating a `@types` dependency, to make new `npm` happy, apparently.
=> feat: test on node 16

package.json, tsconfig.json
Upgrade the baseline to node 10, technically a breaking change.
Upgrade some deps which are technically breaking changes, but shouldn't matter much.
The change of the `typescript` compiler version is most likely to be a breaking change in practice, given their history of breaking mocking or access to internal packages.
This will be a new major version, just in case.
tsconfig docs: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
follows: #96
=> feat(breaking): bump node baseline

package.json, src/core/dep-graph.ts, src/graphlib/graph.ts
Replace `lodash.keys` with `Object.keys`, which should be equivalent for regular inputs, i.e. plain JS objects.
This is a roughly 7% speedup on the committed synthetic benchmarks. This was noticed in the `#fix-event-loop` accidental profiling of this function, which is the slowest thing in prod16 right now, according to that one, very biased source.
=> feat: drop lodash.keys (~7% speedup)

src/graphlib/LICENSE-graphlib
We are currently lacking the graphlib license file
Included this file: https://github.com/dagrejs/graphlib/blob/master/LICENSE
=> Include graphlib license

src/legacy/index.ts, test/legacy/from-dep-tree.test.ts
This commit adds the optional purl string to the legacy dep tree as well. A previous support already added support for the dep graph, but we also need support in dep tree for it.
=> feat: add purl to legacy dep tree

src/core/validate-graph.ts, test/core/validate-graph.test.ts
The purl spec does not include both the source and package names for a purl. Container will be generating purls without the source in the purl, which is why we need to relax the check for matching names.
=> feat: debian purls are validated on package name only

src/core/validate-graph.ts, test/core/validate-graph.test.ts
Ecosystems composer, golang, npm and swift allow for namespaces, which are encoded in the package name. Prior to this, including the Purl namespace in the package name would cause an exception to be thrown during validation.
This PR adds cases during Package URL validation for Purl types `composer`, `golang`, `npm` and `swift`. Since all these types support namespaces, and they have to be encoded in the Snyk package name, this PR prevents validation errors.
Example:
```
{
"name": "@types/ms",
"version": "1.2.3",
"purl": "pkg:npm/%40types/ms@1.2.3" // This would have thrown since "@types" was not taken into account for the package name.
}
```
=> fix: allow for namespaces in Purl validation

src/core/validate-graph.ts, test/core/validate-graph.test.ts
This fixes the validation of a `golang` purl, which may point to a sub-package on its `subpath` component.
=> fix: consider purl subpath when validating golang package

src/core/validate-graph.ts, test/core/validate-graph.test.ts
This adds another case for the validation of `cocoapods` purls. CocoaPods purls encode the spec name as package name, and put the optional sub-spec on the subpath component; as opposed to the DepGraph which will encode spec name and subspec in a single, slash-divided string.
E.g.
```
// Snyk PkgInfo
{
"name": "Adjust/Core",
"version": "4.17.1"
}
// PackageURL
"pkg:cocoapods/Adjust@4.17.1#Core"
```
See specification for `cocoapods` purls here: https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#cocoapods.
=> fix: validation logic of cocoapods purls

src/core/validate-graph.ts, test/core/validate-graph.test.ts
This adds Golang-specific version validation to `validatePackageURL`. It is largely based on the logic in `snyk-go-plugin` here: https://github.com/snyk/snyk-go-plugin/blob/ec49c42d218e0d6d7add92d7b7782c55ff93a557/lib/index.ts#L703-L728
=> fix: validate golang purl version

package.json
Locks down `packageurl-js` to `v1.2.0`. This is the latest version that still allows percent-encuded "+" signs in purl versions.
See tread: https://snyk.slack.com/archives/C01ULJ2H4SF/p1697450545247049
=> fix: lock down packageurl-js version

.circleci/config.yml, .github/CODEOWNERS
[PRODSEC-3273]: Change secrets scanning channel from snyk-on-snyk-analysis_arch to snyk-vuln-alerts-arch
-- 
Committed by prodsec-tools-v2 using octopilot
[PRODSEC-3273]: https://snyksec.atlassian.net/browse/PRODSEC-3273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PRODSEC-3273]: Change secrets scanning channel
